In [26]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import operator
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from matplotlib.pyplot import figure

In [27]:
#Create a path to data
path = r'/Users/chrismace/Desktop/7 Machine Learning'

In [28]:
df = pd.read_csv(os.path.join(path, 'Dataset-weather-prediction-dataset-processed.csv'))

In [29]:
df.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,0.7,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,1.1,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,0.0,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,4.1,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,5.4,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [30]:
df.shape

(22950, 170)

In [33]:
#Reduce your dataset to a single year
df1984 = df[df['DATE'].astype(str).str.contains('1984')] #<-----INSERT YEAR HERE
df1984

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
8766,19840101,1,3,2.1,0.83,1.0275,0.57,0.00,0,6.1,...,7,0.86,1.0138,0.12,0.89,0,0.0,9.2,8.9,11.5
8767,19840102,1,4,2.1,0.82,1.0248,0.56,0.00,0,5.3,...,6,0.80,1.0006,0.12,0.98,0,0.0,9.6,6.8,12.5
8768,19840103,1,8,2.1,0.78,1.0123,0.18,0.45,0,0.0,...,6,0.70,1.0053,0.19,0.65,0,0.8,4.6,1.7,7.3
8769,19840104,1,8,2.1,0.81,1.0178,0.20,0.01,0,0.1,...,5,0.75,1.0248,0.30,0.46,0,1.1,6.6,1.6,9.5
8770,19840105,1,1,2.1,0.75,1.0276,0.52,0.01,0,5.3,...,7,0.79,1.0202,0.14,0.20,0,0.0,7.7,6.3,11.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9127,19841227,12,8,2.1,0.94,1.0162,0.19,0.11,0,0.0,...,5,0.90,1.0145,0.15,0.04,0,0.0,5.2,-0.3,9.0
9128,19841228,12,8,2.1,0.94,1.0297,0.18,0.01,0,0.0,...,8,0.95,1.0224,0.12,1.39,0,0.0,6.6,1.3,11.6
9129,19841229,12,8,2.1,0.78,1.0354,0.13,0.00,0,0.0,...,8,1.00,1.0294,0.16,0.16,0,0.0,11.1,10.4,11.9
9130,19841230,12,5,2.1,0.70,1.0375,0.39,0.00,0,2.3,...,7,0.97,1.0350,0.20,0.02,0,0.1,10.6,8.8,12.4
9131,19841231,12,5,2.1,0.76,1.0327,0.44,0.01,0,4.1,...,8,0.95,1.0350,0.20,0.07,0,0.0,10.6,9.9,11.4

In [34]:
#Scale the weather features
features = df1984
scaled_features = StandardScaler().fit_transform(features)

In [35]:
scaled_features

array([[-1.63954551, -1.59759128, -0.89646846, ..., -0.32210966,
         0.40013305, -0.55739113],
       [-1.63664942, -1.59759128, -0.51846448, ..., -0.22287386,
        -0.08517903, -0.32083599],
       [-1.63375332, -1.59759128,  0.99355145, ..., -1.46332142,
        -1.26379407, -1.55092273],
       ...,
       [ 1.62724898,  1.58967457,  0.99355145, ...,  0.14926041,
         0.74678453, -0.46276908],
       [ 1.63014507,  1.58967457, -0.1404605 , ...,  0.02521566,
         0.37702295, -0.34449151],
       [ 1.63304117,  1.58967457, -0.1404605 , ...,  0.02521566,
         0.63123404, -0.58104665]])

In [36]:
#Run the PCA model, reducing to 18 components
pca = PCA(n_components=18)
principalComponents = pca.fit_transform(scaled_features)

In [37]:
principalComponents

array([[ -6.14361253,  -2.1858269 ,   1.35507014, ...,   1.10038955,
          1.50630201,   0.45528896],
       [ -5.92712357,  -2.46896726,  -0.15920557, ...,   0.56884889,
         -0.10790425,   2.56554382],
       [ -6.75120021,  -5.86706033,  -5.09021073, ...,  -0.93181873,
          0.85803745,   0.49238313],
       ...,
       [-11.91397227,   4.69420537,   7.08536348, ...,   2.38228236,
         -1.55299577,  -0.1784352 ],
       [-12.36515029,   5.201112  ,   7.02082147, ...,   1.46088054,
         -0.5746201 ,  -1.67158841],
       [-12.29180378,   3.81813402,   5.24639975, ...,   0.30264872,
         -0.71252186,  -0.44347124]])

In [39]:
#Make a dataframe of the new components
dfPCA = pd.DataFrame(principalComponents, columns=['PCA1', 'PCA2', 'PCA3', 'PCA4', 'PCA5', 'PCA6', 'PCA7', 'PCA8', 'PCA9', 'PCA10',
                                                   'PCA11', 'PCA12', 'PCA13', 'PCA14', 'PCA15', 'PCA16','PCA17', 'PCA18'])

In [40]:
dfPCA

,PCA1,PCA2,PCA3,PCA4,PCA5,PCA6,PCA7,PCA8,PCA9,PCA10,PCA11,PCA12,PCA13,PCA14,PCA15,PCA16,PCA17,PCA18
0,-6.143613,-2.185827,1.355070,-3.803705,6.559632,-0.366273,-3.708231,-2.442587,-1.566545,-2.222894,-0.291438,1.060551,-1.856316,-2.024154,-0.619184,1.100390,1.506302,0.455289
1,-5.927124,-2.468967,-0.159206,-4.377227,4.664723,-0.144726,-3.337836,-2.329895,-2.633962,-0.549413,-0.638900,-0.053755,-0.225047,-1.716905,-0.518383,0.568849,-0.107904,2.565544
2,-6.751200,-5.867060,-5.090211,-4.260612,6.146911,-3.416869,0.098845,-3.604489,-2.044266,0.054151,0.363665,0.764729,-0.078464,-1.180879,-0.711540,-0.931819,0.858037,0.492383
3,-8.434054,-2.943725,-1.758369,2.834999,3.029474,-2.351093,-0.757916,-0.669963,-1.686836,-0.340452,0.301019,0.777509,-0.729956,-3.638901,-0.667756,-0.960563,0.048956,1.236741
4,-10.303049,1.078335,1.728404,0.942834,3.496579,0.868115,-1.233162,0.521218,-2.008327,1.577904,0.033669,1.332807,-1.224926,-2.681216,-0.722534,-0.408865,0.870116,-0.620386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,-11.243277,0.025904,2.538253,0.239846,-3.442742,0.739403,0.462628,-0.269851,1.555914,-1.106045,0.767688,-1.384454,0.153572,0.625275,0.126744,-0.789679,-1.618755,-1.088540
362,-11.509742,3.406078,5.956387,1.115585,-2.427806,0.518619,0.705377,-1.060615,0.529187,-0.470112,0.650023,-1.891581,-0.110007,0.455443,0.618077,0.958669,-1.534648,-1.851970
363,-11.913972,4.694205,7.085363,3.113597,-1.678263,1.301621,0.988213,0.332064,0.001007,1.244344,0.763155,-1.139679,0.503474,2.519076,1.850697,2.382282,-1.552996,-0.178435
364,-12.365150,5.201112,7.020821,3.689863,-1.021159,1.197597,-0.053901,-0.610655,-0.149894,1.847847,0.378924,-0.442338,-1.900282,0.461322,1.758022,1.460881,-0.574620,-1.671588
365,-12.291804,3.818134,5.246400,0.765298,1.709094,0.791771,-0.211295,-0.029399,1.397471,0.618982,1.594998,-0.427942,-1.108147,2.186083,0.280272,0.302649,-0.712522,-0.443471

In [41]:
dfPCA.to_csv(os.path.join(path, 'PCA_1984.csv'))